

clean:
	rm BigInt.ui
	rm BigInt.uo
	rm Hermes.ui
	rm Hermes.uo
	rm HermesInt.ui
	rm HermesInt.uo
	rm HermesLexer.ui
	rm HermesLexer.uo
	rm HermesParser.ui
	rm HermesParser.uo
	rm HermesPE.ui
	rm HermesPE.uo
	rm HermesReify.ui
	rm HermesReify.uo
	rm HermesTypes.ui
	rm HermesTypes.uo
	rm hi.ui
	rm hi.uo
	rm hpe.ui
	rm hpe.uo
	rm hr.ui
	rm hr.uo
	rm x86.ui
	rm x86.uo
	rm HermesParser.output
	rm HermesParser.sig
	rm hcX64.ui
	rm hcX64.uo
	rm HermesCx64.ui
	rm HermesCx64.uo
	rm HermesCa64.ui
	rm HermesCa64.uo
	rm hcA64.ui
	rm hcA64.uo
	rm a64.ui
	rm a64.uo